services:
  frontend: 
    container_name: frontend
    build: frontend/.
    restart: on-failure
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    links:
      - backend
  backend: 
    container_name: backend
    build: backend/.
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    links:
      - db
  db:
    container_name: db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mtg-collection
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432